### ISSUE TITLE
Comando j.zuraaa

### ISSUE THREAD

**Issue by eiandremoreira** [JudyDiscordBot/Judy#1]
O comando zuraaa tem um pequeno bug que acontece quando o bot não é encontrado, eu fiz uma gambiarra mas quem quiser dar uma força pra mim

**Comment by davipatricio** [comment]
Olá @eiandremoreira, a bot list Zuraaa foi descontinuada há um tempo e foi movida para a Best List Online. Você pode criar um Pull Request para a Best List?
